config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from core.sitemaps import StaticSitemap, ServiceSitemap
from django.contrib.sitemaps.views import sitemap
from config import settings
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView

sitemaps = {
    'static': StaticSitemap,
    'srrvice': ServiceSitemap,
}

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),                            
]
   

urlpatterns  += i18n_patterns(
    path('robots.txt',TemplateView.as_view(template_name='robots.txt', content_type='text/plain')), 
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('', include("core.urls")),
    path('', include("business.urls")),
    path('translation/', include('rosetta.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += i18n_patterns(path('admin/', admin.site.urls),)

else: 
    urlpatterns +=  i18n_patterns(
        path('admin-zone/', admin.site.urls),
        )

core/urls.py
from django.urls import path, re_path
from .views import IndexView, AboutView, RecruitingView, ContactView, QuoteoView,  ServiceView, ServiceDetail, ClientListHTMXView, PortfolioView
from django.urls import path

app_name = 'core'


urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('portfolio', PortfolioView.as_view(), name='portfolio'),
    path('services', ServiceView.as_view(), name='services'),
    path('service_detail/<slug:slug>/', ServiceDetail.as_view(), name='service_detail'),
    path('clients', ClientListHTMXView.as_view(), name='clients'),
    path('about', AboutView.as_view(), name='about'),
    path('hiring', RecruitingView.as_view(), name='hiring'),
    path('contact', ContactView.as_view(), name='contact'),
    path('quote', QuoteoView.as_view(), name='quote'),
    # path('<str:language>/contact/', views.contact, name='contact'),
    # path('<str:language>/about/', views.about, name='about'),
    # path('<str:language>/hiring/', views.hiring, name='hiring'),
    # path('<str:language>/services/', views.services, name='services'),
    # path('<str:language>/index/', views.index, name='index'),
    # path('switch_language/', views.switch_language, name='switch_language'),
]

templates/snippets/breadcrumb.html
<div class="breadcrumb-area rn-bg-color ptb--120 bg_image bg_image--1" data-black-overlay="6">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-inner pt--100 pt_sm--40 pt_md--50">
                    <h2 class="title">{{page_title}}</h2>
                    <ul class="page-list">
                        <li><a href="{% url 'core:index' %}l">{% translate "Home" %}</a></li>
                        <li class="current-page">{{page_title}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

templates/snippets/footer.html
{% load static %}
{% load i18n %}

 <!-- End Page Wrapper  -->
 <footer class="footer-area footer-default">
    <div class="footer-style-2 ptb--30 bg_image bg_image--1" data-black-overlay="6">
        <div class="wrapper plr--50 plr_sm--20">
            <div class="row align-items-center justify-content-between">
                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="inner">
                        <div class="logo text-center text-sm-left mb_sm--20">
                            <a href="#">
                                <img src="{{business.logo.url}}" alt="Logo {{business.name}}" />
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="inner text-center">
                        <ul class="social-share rn-lg-size d-flex justify-content-center liststyle">
                            {% if business.facebook %}
                                <li><a href="{{business.facebook}}"><i class="fab fa-facebook-f"></i></a></li>
                            {% endif %}
                            {% if business.twitter %}
                                <li><a href="{{business.twitter}}"><i class="fab fa-x"></i></a></li>
                            {% endif %}
                            {% if business.instagram %}
                                <li><a href="{{business.instagram}}"><i class="fab fa-instagram"></i></a></li>
                            {% endif %}
                            {% if business.linkedin %}
                                <li><a class="mr--0" href="{{business.linkedin}}"><i class="fab fa-linkedin-in"></i></a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12 col-12">
                    <div class="inner text-lg-right text-center mt_md--20 mt_sm--20">
                        <div class="text">
                            <p>
                                {% blocktranslate %} 
                                    Copyright © 2020 {{business.name}}. All Rights Reserved.
                                {% endblocktranslate %} 
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/snippets/header.html
{% load static %}
{% load i18n %}

<header class="header-area formobile-menu header--transparent black-logo-version ">
    <div class="header-wrapper" id="header-wrapper">
        <div class="header-left">
            <div class="logo">
                <a href="{% url 'core:index' %}">
                    {% if  business.logo %}
                        <img src="{{business.logo.url}}" class="header-logo" alt="{{business.name}}">
                    {% else %}
                        {% translate 'Home' %}
                    {% endif %}
                </a>
            </div>
        </div>
        <div class="header-right">
            <div class="mainmenunav d-lg-block">
                <nav class="main-menu-navbar">
                    <ul class="mainmenu">
                        <li>
                            <a href="{% url 'core:about' %}">{% translate "About" %}</a>
                        </li>
                        <li>
                            <a href="{% url 'core:services' %}">{% translate "Our Services" %}</a>
                        </li>
                        {% comment %} <li class="has-droupdown">
                            <a href="service.html">{% translate "Our Services" %}</a>
                            <ul class="submenu">
                                <li><a href="service.html">{% translate "Service" %}</a></li>
                                <li><a href="service-details.html">{% translate "Service Details" %}</a></li>
                            </ul>
                        </li> {% endcomment %}
                        <li>
                            <a href="{% url 'core:portfolio' %}">{% translate "Portfolio" %}</a>
                        </li>
                        <li>
                            <a href="{% url 'core:contact' %}">{% translate "Contact" %}</a>
                        </li>
                    </ul>
                </nav>

            </div>
            {% comment %} <div class="header-btn">
                <a class="rn-btn" href="#">
                    <span>{% translate "Quote" %}</span>
                </a>
            </div> {% endcomment %}
            <div class="humberger-menu d-block d-lg-none pl--20">
                <span class="menutrigger text-white">
            <i data-feather="menu"></i>
        </span>
            </div>
            <div class="close-menu d-block d-lg-none">
                <span class="closeTrigger">
            <i data-feather="x"></i>
        </span>
            </div>
        </div>
    </div>
</header>

templates/snippets/message.html
{% comment %} {% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible " role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message}}
        </div>
    {% endfor %}
{% endif %} {% endcomment %}


{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            <strong> {{ message}}.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
  {% endfor %}
{% endif %}