config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from core.sitemaps import StaticSitemap, ServiceSitemap
from django.contrib.sitemaps.views import sitemap
from config import settings
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView

sitemaps = {
    'static': StaticSitemap,
    'srrvice': ServiceSitemap,
}

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),                            
]
   

urlpatterns  += i18n_patterns(
    path('robots.txt',TemplateView.as_view(template_name='robots.txt', content_type='text/plain')), 
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('', include("core.urls")),
    path('', include("business.urls")),
    path('translation/', include('rosetta.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += i18n_patterns(path('admin/', admin.site.urls),)

else: 
    urlpatterns +=  i18n_patterns(
        path('admin-zone/', admin.site.urls),
        )

core/urls.py
from django.urls import path, re_path
from .views import IndexView, AboutView, RecruitingView, ContactView, QuoteoView,  ServiceView, ServiceDetail, ClientListHTMXView, PortfolioView
from django.urls import path

app_name = 'core'


urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('portfolio', PortfolioView.as_view(), name='portfolio'),
    path('services', ServiceView.as_view(), name='services'),
    path('service_detail/<slug:slug>/', ServiceDetail.as_view(), name='service_detail'),
    path('clients', ClientListHTMXView.as_view(), name='clients'),
    path('about', AboutView.as_view(), name='about'),
    path('hiring', RecruitingView.as_view(), name='hiring'),
    path('contact', ContactView.as_view(), name='contact'),
    path('quote', QuoteoView.as_view(), name='quote'),
    # path('<str:language>/contact/', views.contact, name='contact'),
    # path('<str:language>/about/', views.about, name='about'),
    # path('<str:language>/hiring/', views.hiring, name='hiring'),
    # path('<str:language>/services/', views.services, name='services'),
    # path('<str:language>/index/', views.index, name='index'),
    # path('switch_language/', views.switch_language, name='switch_language'),
]

core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Contact,  Quote, Hiring
from django.utils.translation import gettext as _
from django.core.exceptions import ValidationError


CHOICES = (
    ('S1' ,'Cycle Moyen'),
    ('S2' ,'Niveau Secondaire'),
    ('S3' ,'Niveau Terminal'),
    ('S4' ,'Formation Professionnelle '),
    ('S5' ,'Baccalauréat'),
    ('S6' ,'Niveau Universitaire'),
)
CHOICES_YES = (
    ('1' ,'YES'),
    ('2' ,'NO '),

)

class ContactForm(ModelForm) :
    username = forms.CharField(required=False)
    name = forms.CharField(required=True)
    phone = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    entreprise = forms.CharField(required=False)

    class Meta: 
        model = Contact 
        fields = (
                'name',
                'email',
                'phone',
                'entreprise',
                # 'service',
                'subject',
                'message',)
        
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        if username:
            raise ValidationError(
                    "BAD BOT"
                )
    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        self.fields['name'].label = "Full name *"
        self.fields['email'].label = "Email *"
        self.fields['phone'].label = "Phone *"
        self.fields['entreprise'].label = "Company "
        self.fields['subject'].label = "subject "
        self.fields['message'].label = "message "
        self.fields['username'].widget = forms.HiddenInput()
        # self.fields['service'].widget.attrs.update({
        #         "class": "select-form select-contact", 
        #         "placeholder" : "Select service"
        #     }) 
        self.fields['message'].widget.attrs.update({
                "class": "subject", 
            }) 
        
class QuoteForm(ModelForm) :
    username = forms.CharField(required=False)
    entreprise = forms.CharField(required=True)
    phone = forms.CharField(required=True)
    service = forms.CharField(required=False)
    class Meta: 
        model = Quote 
        fields = (
            'email',
            'phone',
            'entreprise', 
            'service'
            )
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        if username:
            raise ValidationError(
                    "BAD BOT"
                )
    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        self.fields['entreprise'].label = "Company *"
        self.fields['email'].label = "Email *"
        self.fields['phone'].label = "Phone *"
        self.fields['service'].label = "service "
        self.fields['username'].widget = forms.HiddenInput()
        self.fields['service'].widget.attrs.update({
                "class": "select-form select-contact", 
                "placeholder" : "Select service"
            }) 
     

class HiringForm(ModelForm) :
    username = forms.CharField(required=False)
    name = forms.CharField(required=True)
    phone = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    birth_date = forms.DateField(required=True, widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}), input_formats=["%Y-%m-%d"])
    birth_place = forms.CharField(required=False)
    niveau = forms.ChoiceField(required=False, choices=CHOICES)
    # permis = forms.BooleanField(required=False, initial=False)
    # passeport = forms.BooleanField(required=False, initial=False)
    # army = forms.BooleanField(required=False, initial=False)
    cv_file = forms.FileField(required=False)
    # message = forms.CharField(required=False)

    class Meta: 
        model = Hiring 
        fields = (
                'name',
                'email',
                'phone',
                'niveau',
                'birth_date',
                'birth_place',
                # 'permis',
                # 'passeport',
                # 'army',
                'cv_file',
                'message',

                )
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        if username:
            raise ValidationError(
                    "BAD BOT"
                )   
    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        self.fields['name'].label = "Full name *"
        self.fields['email'].label = "Email *"
        self.fields['phone'].label = "Phone *"
        self.fields['birth_date'].label = "Birth date *"
        self.fields['birth_place'].label = "Birth place "
        self.fields['niveau'].label = "niveau "
        # self.fields['permis'].label = "driving licence "
        # self.fields['passeport'].label = "passeport "
        # self.fields['army'].label = "Carte jaune "
        self.fields['cv_file'].label = "cv_file "
        self.fields['message'].label = "message "

        self.fields['username'].widget = forms.HiddenInput()
        self.fields['niveau'].widget.attrs.update({
                "class": "select-form select-contact", 
                "placeholder" : "Select service"
            }) 
        # self.fields['permis'].widget.attrs.update({
        #         # "class": "checkbox", 
        #         "type":"radio",
        #         "placeholder" : "driving licence"
        #     }) 

core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import TemplateView, ListView , DetailView, CreateView
from django.views.generic.edit import FormView
from django.http import JsonResponse
from business import translation
from django.contrib import messages
from config import settings 
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from business.models import  Slide
from core.models import Client, Service, Proof, Contact, Quote, Hiring,About, ProtfolioCategory, PortfolioItem, TeamMember
from core.forms import ContactForm, QuoteForm, HiringForm
from django.shortcuts import redirect
# from django.utils.translation import LANGUAGE_SESSION_KEY
from django.shortcuts import redirect
from django.utils.translation import activate
from django.conf import settings
from django.shortcuts import redirect
from django.utils.translation import activate
from django.conf import settings
from django.views.decorators.cache import never_cache





############### INDEX ###############
class IndexView(TemplateView):
    def get_template_names(self):
        # if self.request.LANGUAGE_CODE == 'ar':
        #     return ['rtl/index.html']
        # else:
        return ['index.html']
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context["home_services"] =  Service.objects.filter(display_on_home=True)
        context["banner"]   = Slide.objects.filter(placement=1, is_active=True).first()
        context["proofs"]   = Proof.objects.filter(is_active=True)
        context["about"]   = About.objects.first()
        context["portoflio_items"]   = PortfolioItem.objects.filter(is_active=True).select_related('category')
        
        return context

############### ABOUT ###############
class AboutView(TemplateView):
    def get_template_names(self):
        # if self.request.LANGUAGE_CODE == 'ar':
        #     return ['rtl/about.html']
        # else:
        return ['about.html']
    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context["about"]        = About.objects.first()
        context["banner"]   = Slide.objects.filter(placement=2, is_active=True).first()
        context["team_members"] = TeamMember.objects.filter(is_active=True)
        return context

############### SERVICES ###############
##### LIST
class ServiceView(ListView):
    def get_template_names(self):
        # if self.request.LANGUAGE_CODE == 'ar':
        #     return ['rtl/services.html']
        # else:
        return ['services.html']
    model = Service
    context_object_name ="services"


############### PORTFOLIO ###############
##### LIST
class PortfolioView(ListView):
    def get_template_names(self):
        # if self.request.LANGUAGE_CODE == 'ar':
        #     return ['rtl/services.html']
        # else:
        return ['portfolio.html']
    model = PortfolioItem
    context_object_name ="portfolio_items"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["portfolio_categories"] =  ProtfolioCategory.objects.prefetch_related('portfolio_items').all()
        return context
    

class ServiceDetail(DetailView):
    model = Service
    def get_template_names(self):
        # if self.request.LANGUAGE_CODE == 'ar':
        #     return ['rtl/services_detail.html']
        # else:
        return ['services_detail.html']
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["services"] =Service.objects.all()
        context["abouts"] =About.objects.all()
        return context

############### CONTACT ###############
class ContactView(SuccessMessageMixin, FormView):
    def get_template_names(self):
        # if self.request.LANGUAGE_CODE == 'ar':
        #     return ['rtl/contact.html']
        # else:
        return ['contact.html']
    form_class= ContactForm
    model = Contact 
    success_message = "We received your message, you will be contacted you soon."
    success_url = reverse_lazy('core:contact')
    def get_context_data(self, **kwargs):
        context = super(ContactView, self).get_context_data(**kwargs)
        contact_form = ContactForm
        context['form'] = contact_form 
        context["banner"]   = Slide.objects.filter(placement=3, is_active=True).first()
        context["services"] = Service.objects.all()
        return context
    def form_valid(self, form):
        if form.is_valid() :
            self.object = form.save()
            message = _("We received your message, you will be contacted soon.")
            messages.success(self.request, str(message))
        else:
            message = _("Error occures when submitting the message, please check the required fields.")
            messages.error(self.request, str(message))
        return HttpResponseRedirect(self.get_success_url())
    
############### QUOTE ###############
class QuoteoView(SuccessMessageMixin, CreateView):
    def get_template_names(self):
        # if self.request.LANGUAGE_CODE == 'ar':
        #     return ['rtl/quote.html']
        # else:
        return ['quote.html']
    form_class= QuoteForm
    model = Quote 
    success_message = "We received your message, you will be contacted you soon."
    success_url = reverse_lazy('business:quote')
    def get_context_data(self, **kwargs):
        context = super(QuoteoView, self).get_context_data(**kwargs)
        quote_form = QuoteForm
        context['form'] = quote_form  
        context["services"] =Service.objects.all()
        return context
    def form_valid(self, form):
        if form.is_valid() :
            self.object = form.save()
            message = _("We received your message, you will be contacted soon.")
            messages.success(self.request, str(message))
        else:
            message = _("Error occures when submitting the message, please check the required fields.")
            messages.error(self.request, str(message))
        return HttpResponse(status=204) 
    
############### HIRING ###############
class RecruitingView(SuccessMessageMixin, CreateView):
    def get_template_names(self):
        # if self.request.LANGUAGE_CODE == 'ar':
        #     return ['rtl/hiring.html']
        # else:
        return ['hiring.html']
    form_class= HiringForm
    model = Hiring 
    success_message = "We received your message, you will be contacted you soon." 
    success_url = reverse_lazy('core:hiring')
    def get_context_data(self, **kwargs):
        context = super(RecruitingView, self).get_context_data(**kwargs)
        hiring_form = HiringForm
        context['form'] = hiring_form  
        return context
    def form_valid(self, form):
        if form.is_valid() :
            self.object = form.save()
            message = _("We received your message, you will be contacted soon.")
            messages.success(self.request, str(message))
        else:
            message = _("Error occures when submitting the message, please check the required fields.")
            messages.error(self.request, str(message))
        return HttpResponse(status=204) 






############### Clients ###############
##### LIST
class ClientListHTMXView(ListView):
    def get_template_names(self):
        # if self.request.LANGUAGE_CODE == 'ar':
        #     return ['rtl/services.html']
        # else:
        return ['snippets/clients-block.html']
    model = Client
    context_object_name ="clients"
    

    
class PortfolioView(TemplateView):
    template_name = 'portfolio.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["portfolio_items"] =  PortfolioItem.objects.select_related('category').all()
        context["portoflio_categories"] =  ProtfolioCategory.objects.prefetch_related('portfolio_items').all()
        return context

core/templates/index.html
{% extends base_template %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info for LANGUAGE_CODE as lang %}
{% get_language_info_list for LANGUAGES as languages %}

{% block content %} 

<main class="page-wrapper">
    <div class="rn-slider-area">
        <div class="slide slide-style-1 slider-fixed--height d-flex align-items-center bg_image bg_image--1" data-black-overlay="6">
            <div class="container position-relative">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="inner">
                            <h1 class="title theme-gradient">{{business.title}}</h1>
                        </div>
                    </div>
                </div>
                {% comment %} <div class="service-wrapper service-white">
                    <div class="row">

                        <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                            <div class="single-service service__style--3 text-white">
                                <div class="icon">
                                    <img src="{% static 'images/icons/icon-01.png' %}" alt="Creative Agency" />
                                </div>
                                <div class="content">
                                    <h3 class="title">Business Stratagy</h3>
                                    <p>There are many variations of passages of Lorem Ipsum available, but the
                                        majority have suffered.</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                            <div class="single-service service__style--3 text-white">
                                <div class="icon">
                                    <img src="{% static 'images/icons/icon-02.png' %}" alt="Creative Agency" />
                                </div>
                                <div class="content">
                                    <h3 class="title">Website Development</h3>
                                    <p>There are many variations of passages of Lorem Ipsum available, but the
                                        majority have suffered.</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                            <div class="single-service service__style--3 text-white">
                                <div class="icon">
                                    <img src="{% static 'images/icons/icon-03.png' %}" alt="Creative Agency" />
                                </div>
                                <div class="content">
                                    <h3 class="title">Marketing & Reporting</h3>
                                    <p>There are many variations of passages of Lorem Ipsum available, but the
                                        majority have suffered.</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div> {% endcomment %}
            </div>
        </div>
    </div>
    <div class="rn-service-area rn-section-gap bg_color--1">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title text-center mb--30">
                        <h2>{% translate "Our Services" %}</h2>
                        <p>{% translate "SARL BIOPIC répond à vos objectifs dans vos projets audiovisuels de différents types" %}</p>
                    </div>
                </div>
            </div>
            <div class="row">
                
                {% for service in  home_services %}
                    <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                        <div class="single-service service__style--4 large-size text-center">
                            <a href="service-details.html">
                                <div class="service">
                                    <div class="icon">
                                        {% if service.icon %}
                                            <img src="{{service.icon.url}}" alt="">
                                        {% endif %}
                                    </div>
                                    <div class="content">
                                        <h3 class="title">{{service.name}}</h3>
                                        <p>{{service.description|default_if_none:""}}</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="about-area about-position-top pb--120">
        <div class="about-wrapper">
            <div class="container">
                <div class="row row--35 align-items-center">
                    <div class="col-lg-5 col-md-12">
                        <div class="thumbnail">
                            <img class="w-100" src="{{banner.image.url}}" alt="About Images" />
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-12">
                        <div class="about-inner inner">
                            <div class="section-title">
                                <h2 class="title">{% translate "About" %}</h2>
                                <p class="description">{{business.about|safe}}</p>
                            </div>
                            <div class="row mt--30 mt_sm--10">
                                <div class="col-lg-6 col-md-12 col-sm-12 col-12">
                                    <div class="about-us-list">
                                        <h3 class="title">Who we are</h3>
                                        <p>There are many vtions of passages of Lorem Ipsum available, but the
                                            majority have suffered.</p>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12 col-sm-12 col-12">
                                    <div class="about-us-list">
                                        <h3 class="title">Who we are</h3>
                                        <p>There are many vtions of passages of Lorem Ipsum available, but the
                                            majority have suffered.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    <div class="rn-portfolio-area rn-section-gap bg_color--1">
        <div class="portfolio-sacousel-inner pb--30">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-title text-center mb--20 mb_sm--0 mb_md--0">
                            <h2 class="title">{% translate "Our Works" %}</h2>
                                <div class="service-btn"><a class="btn-transparent rn-btn-dark" href="/service"><span
                                    class="text">{% translate "View our portfolio" %}</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="portfolio-slick-activation rn-slick-activation item-fluid rn-slick-dot mt--40 mt_sm--40" 
                    data-slick-options='{
                        "spaceBetween": 15, 
                        "slidesToShow": 5, 
                        "slidesToScroll": 1, 
                        "arrows": true, 
                        "infinite": true,
                        "dots": true
                    }' 
                    data-slick-responsive='[
                        {"breakpoint":1600, "settings": {"slidesToShow": 4}},
                        {"breakpoint":1200, "settings": {"slidesToShow": 3}},
                        {"breakpoint":890, "settings": {"slidesToShow": 3}},
                        {"breakpoint":590, "settings": {"slidesToShow": 2}},
                        {"breakpoint":480, "settings": {"slidesToShow": 1}}
                    ]'>
                {% for p_item in portoflio_items %}
                   {% include 'snippets/portfolio-item.html' %}
                {% endfor %}
            </div>
        </div>
    </div>

    
    {% if proofs %}
        <div class="rn-counterup-area pt--25 pb--110 bg_color--1">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-title text-center">
                            <h3 class="fontWeight500">{% translate "Social proof" %}</h3>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for proof in proofs %}
                        <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                            <div class="rn-counterup counterup_style--1">
                                <h5 class="counter count">{{proof.number}}</h5>
                                <p class="description">{{proof.text}}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}

    {% if clients %}
        <div class="rn-brand-area brand-separation">
            <div class="container">
                <div class="row">
                    <div class="section-title text-center">
                        <h2 class="title">{% translate "Our Clients" %}</h2>
                    </div>
                    <div class="col-lg-12"
                        hx-get="{% url 'core:clients' %}"
                        hx-trigger="load"
                        hx-target="this"
                        hx-swap="innerHTML"
                        >
                    </div>
                </div>
            </div>
        </div>
    {% endif %}


</main>
{% endblock content %}

core/templates/portfolio.html
{% extends base_template %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}
 
{% block content %}
    {% include 'snippets/breadcrumb.html' with page_title="Portfolio" %}
    

    <main class="page-wrapper">
        <div class="rn-portfolio-area rn-section-gap bg_color--1">
            <div class="creative-portfolio-wrapper plr--10">
                <div class="row  row--5 d-flex justify-content-center">
                    {% for p_item in portfolio_items %}
                        <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                            {% include 'snippets/portfolio-item.html' %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>

{% endblock content %}

core/templates/quote.html
{% extends base_template %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}
{% block content %}
    <div class="rts-breadcrumb-area breadcrumb-bg bg_image" {% if contact.image_breadcrumb %} style="background-image: url({{contact.image_breadcrumb.url}});" {% endif %} >
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 breadcrumb-1">
                    <h1 class="title">{% trans 'Hiring' %}</h1>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                    <div class="bread-tag">
                        <a href="{% url 'core:index' %}">{% trans 'Home' %}</a>
                        <span> / </span>
                        <a href="{% url 'core:contact' %}" class="active">{% trans 'Quote' %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="rts-contact-form-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="rts-contact-fluid rts-section-gap">
                        <div class="rts-title-area contact-fluid text-center mb--50">
                            <p class="pre-title">
                                {% trans 'Quote' %}
                            </p>
                            <h2 class="title">{% trans "Send us a message to get a quote." %}</h2>
                        </div>
                        <div class="form-wrapper">
                            {% include 'message.html' %}
                            <div id="success-message">
                            </div>
                            <form method="post" action="{% url 'core:quote' %}" >
								{% csrf_token %}
                                {% with WIDGET_ERROR_CLASS='is-invalid'  %}
                                    {% for field in form %}
                                        <div class="name-email">
                                            {% comment %} <label for="{{field.id}}" class="required"> {{field.label}} </label> {% endcomment %}
                                            {% render_field field|add_class:"form-control" placeholder=field.label %}
                                            <div class="invalid-feedback">
                                                {{ field.errors }} 
                                            </div>
                                        </div>
                                    {% endfor %} 
                                {% endwith %}   
                                <button type="submit" class="rts-btn btn-primary">{% trans 'Submit' %}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}